name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  provider: ^6.1.5
  shimmer: ^3.0.0
  supabase_flutter: ^2.0.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
